### ISSUE TITLE
上传jsondata，执行upload.sh报错

### ISSUE THREAD

**Issue by bluecode2017** [BitTigerInst/BitTiger-CS504-FAQ#15]
用docker-compose up -d启动mysql后，执行mvn clean install, 执行./target/Running-Information-Analysis-Service-1.0.0.BUILD-SNAPSHOT.jar，然后再执行./upload-running-informations.sh 就报错。

upload-running-informations.sh 文件内容是
```
#!/usr/bin/env bash
curl -H "Content-type: application/json" localhost:8080/bulkUpload  -d @runningInformations.json
```

执行报错
![image](https://cloud.githubusercontent.com/assets/24232532/24980236/4140c18c-1f8c-11e7-8b1c-ab3135736a0e.png)
![image](https://cloud.githubusercontent.com/assets/24232532/24980261/5777651e-1f8c-11e7-8664-11f903e81f9e.png)

**Comment by hackjutsu** [comment]
@bluecode2017 

如何重现这个问题呢？

**Comment by bluecode2017** [comment]
这个问题没解决。可以一直重现，我启动mysql后，执行mvn clean install,  执行./target/Running-Information-Analysis-Service-1.0.0.BUILD-SNAPSHOT.jar，然后再执行./upload-running-informations.sh 就报错

**Comment by hackjutsu** [comment]
@bluecode2017 

其实我是想问我要如何在自己的电脑上重现这个问题。。。

比如说;
1. 你的程序代码是什么？
2. 别人怎样利用你的代码在ta电脑上启动程序
3. 程序启动以后要如何触发这个错误
