### ISSUE TITLE
Can we use Spring Boot for Search Ad system?

### ISSUE THREAD

**Issue by bihjuchiu** [BitTigerInst/BitTiger-CS504-FAQ#38]
Is it possible to use Spring Boot, Spring Data for creating SearchAds system (Index builder, AdsEngine... etc.)? Spring also provide RPC support, so can we use all the microservices technologies we learned at the first month on SearchAds project? Is there any concern for using it?(like too many resources used with Spring?) How is this done in industry?

**Comment by hackjutsu** [comment]
我觉得没问题啊

**Comment by bittiger-java** [comment]
完全可以用。Spring 不会使用很多的resources。 Embedded Tomcat会有一些memory footprint，但是我在课上讲过这样子做比standalone tomcat的好处

**Comment by bihjuchiu** [comment]
太好了，谢谢！
