### ISSUE TITLE
cannot resolve symbol "SpringApplication"

### ISSUE THREAD

**Issue by xiayank** [BitTigerInst/BitTiger-CS504-FAQ#5]
![image](https://cloud.githubusercontent.com/assets/23108630/24626431/e66db8b2-1876-11e7-834d-43042e3b1cbe.png)
我的intellij不知道为什么不会自动import，我已经确定选了enable auto-complete 最开始的时候。POM里面跟老师写的也一样，而且没有报错。

**Comment by xiayank** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>hello-world-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
        <relativePath/>
    </parent>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-start-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven.plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by xiayank** [comment]
解决了：File | Invalidate Caches

**Comment by hackjutsu** [comment]
这是我上课跟着老师写的code：https://github.com/hackjutsu/bittiger-cs504
