### ISSUE TITLE
输入vagrant up提示Box 'base' could not be found.

### ISSUE THREAD

**Issue by JadeLSQ** [BitTigerInst/BitTiger-CS504-FAQ#6]
<img width="519" alt="screen shot 2017-04-03 at 21 38 21" src="https://cloud.githubusercontent.com/assets/25063970/24629943/1e601118-18bb-11e7-87fb-0d5957363d17.png">

群友说要装Virtual box最新版，但是装完以后打开Virtual box是这样

<img width="766" alt="screen shot 2017-04-03 at 22 21 43" src="https://cloud.githubusercontent.com/assets/25063970/24630241/385c2f9c-18bc-11e7-87fd-2d6f5784140b.png">

再点击check以后是这样

<img width="769" alt="screen shot 2017-04-03 at 22 26 15" src="https://cloud.githubusercontent.com/assets/25063970/24630339/9d7f6e3e-18bc-11e7-81b9-ff3fe1cbcc3e.png">

就不知道怎么办了

**Comment by hackjutsu** [comment]
你跑了`git clone`这一步了吗？
```
git clone https://github.com/bittiger-java/vagrant-workstation.git
cd vagrant-workstation
vagrant up
```

**Comment by JadeLSQ** [comment]
太好了，我输入了hackjutsu您给的指令，得到default: Which interface should the network bridge to?咋办

**Comment by hackjutsu** [comment]
@JadeLSQ 给出什么选项呢？一般来说，选择第一个就行。

**Comment by JadeLSQ** [comment]
好了。我输入了vagrant ssh, 出现这个页面，正常吗？
<img width="492" alt="screen shot 2017-04-03 at 23 28 51" src="https://cloud.githubusercontent.com/assets/25063970/24632756/adccbea0-18c5-11e7-9d2a-ee034e7d33d3.png">

**Comment by hackjutsu** [comment]
@JadeLSQ 不需要跑`vagrant ssh`，跑`vagrant reload`

**Comment by JadeLSQ** [comment]
https://www.vagrantup.com/intro/getting-started/provisioning.html
您的意思是从这一步开始都不用管了吗？

**Comment by hackjutsu** [comment]
@JadeLSQ 按照电子书里的步骤来配置环境就可以了。

```
git clone https://github.com/bittiger-java/vagrant-workstation.git
cd vagrant-workstation
vagrant up
```
结束以后
```
vagrant reload
```
一切顺利的话，我们会看到下面的登录界面
![vagrant_login](https://cloud.githubusercontent.com/assets/7756581/24634889/170865fe-1885-11e7-80de-47e9471adae9.png)

**Comment by JadeLSQ** [comment]
是不是安装过程中不能关闭Terminal 的... 我昨天做完vagrant reload就关掉去睡觉了，起床再打开Terminal 发现不行了。 另外，我没有出现您上面那个界面。

**Comment by hackjutsu** [comment]
@JadeLSQ 是的，安装在VM里哦

**Comment by JadeLSQ** [comment]
<img width="1159" alt="screen shot 2017-04-04 at 23 05 18" src="https://cloud.githubusercontent.com/assets/25063970/24678574/59f0370a-198b-11e7-937d-dc81b0cdd612.png">
是在这里选择 ~/tools 文件夹吗？这个文件夹是要自己创建还是Ubuntu里面本来就有的？

**Comment by hackjutsu** [comment]
@JadeLSQ 自己创立的
```
mkdir ~/tools
```

**Comment by hackjutsu** [comment]
@JadeLSQ 参考https://github.com/BitTigerInst/BitTiger-CS504-FAQ/issues/7
